stages:
  - install
  - test
  - build
  - deploy
  - cleanup

variables:
  NODE_ENV: 'production'

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: install
  image: node:22.11.0
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/

run_tests:
  stage: test
  image: node:22.11.0
  script:
    - echo "Pruebas realizadas"
    - exit 0

build_project:
  stage: build
  image: node:22.11.0
  script:
    - apt-get update && apt-get install -y zip
    - npm run build
    - zip -r dist.zip dist/
    
  artifacts:
    paths:
      - dist.zip

deploy_to_azure:
  stage: deploy
  image: mcr.microsoft.com/azure-cli
  script:
    - az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
    - az webapp deploy --resource-group $AZURE_RESOURCE_GROUP --name $AZURE_APP_NAME --src-path dist.zip
  only:
    - main

cleanup:
  stage: cleanup
  script:
    - echo "Limpiando recursos temporales..."
