name: Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Obtener el c贸digo desde el repositorio
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Configurar la versi贸n de Node.js
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # 3. Instalar dependencias, compilar y ejecutar pruebas
      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      # 4. Empaquetar el artefacto (c贸digo listo para desplegar)
      - name: Zip artifact for deployment
        run: zip -r release.zip ./

      # 5. Cargar el artefacto resultante para el job de despliegue
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      # 1. Descargar el artefacto generado en el job anterior
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # 2. Desempaquetar el artefacto
      - name: Unzip artifact
        run: unzip release.zip

      # 3. Autenticarse en Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      # 4. Desplegar la aplicaci贸n en Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'to-do-list-api'
          slot-name: 'Production'
          package: .
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
